package com.unicom.model;

public class TMlbRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.id
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.wxOrderId
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String wxOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.OrderSign
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String orderSign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.wxOrderNo
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String wxOrderNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.Amount
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */

	private Double amount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.ICCID
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String ICCID;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.SIM
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String SIM;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.IMSI
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String IMSI;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.IMEI
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String IMEI;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.PackageName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String packageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.PayState
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String payState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.PayTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.CreateTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.PayMenter
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String payMenter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.isToActiveOrder
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String isToActiveOrder;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.isPush
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String isPush;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.holdName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String holdName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.oldPackageName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String oldPackageName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.isFirst
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String isFirst;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.simState
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String simState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.activeTimespan
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String activeTimespan;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.payEEName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String payEEName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.accessEEName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String accessEEName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.platformType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String platformType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.RenewalsStatus
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String renewalsStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.RenewalsStatusMsg
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String renewalsStatusMsg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.SimFromType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String simFromType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.Tag
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.TradeType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String tradeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.SourceType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String sourceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.Receivables
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String receivables;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.isExpireRenewals
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String isExpireRenewals;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.MonthUsageData
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String monthUsageData;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_mlb_record.recordTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	private String recordTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.id
	 * @return  the value of t_mlb_record.id
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.id
	 * @param id  the value for t_mlb_record.id
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.wxOrderId
	 * @return  the value of t_mlb_record.wxOrderId
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getWxOrderId() {
		return wxOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.wxOrderId
	 * @param wxOrderId  the value for t_mlb_record.wxOrderId
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setWxOrderId(String wxOrderId) {
		this.wxOrderId = wxOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.OrderSign
	 * @return  the value of t_mlb_record.OrderSign
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getOrderSign() {
		return orderSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.OrderSign
	 * @param orderSign  the value for t_mlb_record.OrderSign
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setOrderSign(String orderSign) {
		this.orderSign = orderSign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.wxOrderNo
	 * @return  the value of t_mlb_record.wxOrderNo
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getWxOrderNo() {
		return wxOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.wxOrderNo
	 * @param wxOrderNo  the value for t_mlb_record.wxOrderNo
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setWxOrderNo(String wxOrderNo) {
		this.wxOrderNo = wxOrderNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.Amount
	 * @return  the value of t_mlb_record.Amount
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public Double getAmount() {
		return amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.Amount
	 * @param amount  the value for t_mlb_record.Amount
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setAmount(Double amount) {
		this.amount = amount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.ICCID
	 * @return  the value of t_mlb_record.ICCID
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getICCID() {
		return ICCID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.ICCID
	 * @param ICCID  the value for t_mlb_record.ICCID
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setICCID(String ICCID) {
		this.ICCID = ICCID;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.SIM
	 * @return  the value of t_mlb_record.SIM
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getSIM() {
		return SIM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.SIM
	 * @param SIM  the value for t_mlb_record.SIM
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setSIM(String SIM) {
		this.SIM = SIM;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.IMSI
	 * @return  the value of t_mlb_record.IMSI
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getIMSI() {
		return IMSI;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.IMSI
	 * @param IMSI  the value for t_mlb_record.IMSI
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setIMSI(String IMSI) {
		this.IMSI = IMSI;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.IMEI
	 * @return  the value of t_mlb_record.IMEI
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getIMEI() {
		return IMEI;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.IMEI
	 * @param IMEI  the value for t_mlb_record.IMEI
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setIMEI(String IMEI) {
		this.IMEI = IMEI;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.PackageName
	 * @return  the value of t_mlb_record.PackageName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getPackageName() {
		return packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.PackageName
	 * @param packageName  the value for t_mlb_record.PackageName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setPackageName(String packageName) {
		this.packageName = packageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.PayState
	 * @return  the value of t_mlb_record.PayState
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getPayState() {
		return payState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.PayState
	 * @param payState  the value for t_mlb_record.PayState
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setPayState(String payState) {
		this.payState = payState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.PayTime
	 * @return  the value of t_mlb_record.PayTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.PayTime
	 * @param payTime  the value for t_mlb_record.PayTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setPayTime(String payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.CreateTime
	 * @return  the value of t_mlb_record.CreateTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.CreateTime
	 * @param createTime  the value for t_mlb_record.CreateTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setCreateTime(String createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.PayMenter
	 * @return  the value of t_mlb_record.PayMenter
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getPayMenter() {
		return payMenter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.PayMenter
	 * @param payMenter  the value for t_mlb_record.PayMenter
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setPayMenter(String payMenter) {
		this.payMenter = payMenter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.isToActiveOrder
	 * @return  the value of t_mlb_record.isToActiveOrder
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getIsToActiveOrder() {
		return isToActiveOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.isToActiveOrder
	 * @param isToActiveOrder  the value for t_mlb_record.isToActiveOrder
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setIsToActiveOrder(String isToActiveOrder) {
		this.isToActiveOrder = isToActiveOrder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.isPush
	 * @return  the value of t_mlb_record.isPush
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getIsPush() {
		return isPush;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.isPush
	 * @param isPush  the value for t_mlb_record.isPush
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setIsPush(String isPush) {
		this.isPush = isPush;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.holdName
	 * @return  the value of t_mlb_record.holdName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getHoldName() {
		return holdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.holdName
	 * @param holdName  the value for t_mlb_record.holdName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setHoldName(String holdName) {
		this.holdName = holdName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.oldPackageName
	 * @return  the value of t_mlb_record.oldPackageName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getOldPackageName() {
		return oldPackageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.oldPackageName
	 * @param oldPackageName  the value for t_mlb_record.oldPackageName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setOldPackageName(String oldPackageName) {
		this.oldPackageName = oldPackageName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.isFirst
	 * @return  the value of t_mlb_record.isFirst
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getIsFirst() {
		return isFirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.isFirst
	 * @param isFirst  the value for t_mlb_record.isFirst
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setIsFirst(String isFirst) {
		this.isFirst = isFirst;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.simState
	 * @return  the value of t_mlb_record.simState
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getSimState() {
		return simState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.simState
	 * @param simState  the value for t_mlb_record.simState
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setSimState(String simState) {
		this.simState = simState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.activeTimespan
	 * @return  the value of t_mlb_record.activeTimespan
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getActiveTimespan() {
		return activeTimespan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.activeTimespan
	 * @param activeTimespan  the value for t_mlb_record.activeTimespan
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setActiveTimespan(String activeTimespan) {
		this.activeTimespan = activeTimespan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.payEEName
	 * @return  the value of t_mlb_record.payEEName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getPayEEName() {
		return payEEName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.payEEName
	 * @param payEEName  the value for t_mlb_record.payEEName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setPayEEName(String payEEName) {
		this.payEEName = payEEName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.accessEEName
	 * @return  the value of t_mlb_record.accessEEName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getAccessEEName() {
		return accessEEName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.accessEEName
	 * @param accessEEName  the value for t_mlb_record.accessEEName
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setAccessEEName(String accessEEName) {
		this.accessEEName = accessEEName;
	}


	public String getPlatformType() {
		return platformType;
	}

	public void setPlatformType(String platformType) {
		this.platformType = platformType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.RenewalsStatus
	 * @return  the value of t_mlb_record.RenewalsStatus
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getRenewalsStatus() {
		return renewalsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.RenewalsStatus
	 * @param renewalsStatus  the value for t_mlb_record.RenewalsStatus
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setRenewalsStatus(String renewalsStatus) {
		this.renewalsStatus = renewalsStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.RenewalsStatusMsg
	 * @return  the value of t_mlb_record.RenewalsStatusMsg
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getRenewalsStatusMsg() {
		return renewalsStatusMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.RenewalsStatusMsg
	 * @param renewalsStatusMsg  the value for t_mlb_record.RenewalsStatusMsg
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setRenewalsStatusMsg(String renewalsStatusMsg) {
		this.renewalsStatusMsg = renewalsStatusMsg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.SimFromType
	 * @return  the value of t_mlb_record.SimFromType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getSimFromType() {
		return simFromType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.SimFromType
	 * @param simFromType  the value for t_mlb_record.SimFromType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setSimFromType(String simFromType) {
		this.simFromType = simFromType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.Tag
	 * @return  the value of t_mlb_record.Tag
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.Tag
	 * @param tag  the value for t_mlb_record.Tag
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setTag(String tag) {
		this.tag = tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.TradeType
	 * @return  the value of t_mlb_record.TradeType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.TradeType
	 * @param tradeType  the value for t_mlb_record.TradeType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.SourceType
	 * @return  the value of t_mlb_record.SourceType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getSourceType() {
		return sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.SourceType
	 * @param sourceType  the value for t_mlb_record.SourceType
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setSourceType(String sourceType) {
		this.sourceType = sourceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.Receivables
	 * @return  the value of t_mlb_record.Receivables
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getReceivables() {
		return receivables;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.Receivables
	 * @param receivables  the value for t_mlb_record.Receivables
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setReceivables(String receivables) {
		this.receivables = receivables;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.isExpireRenewals
	 * @return  the value of t_mlb_record.isExpireRenewals
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getIsExpireRenewals() {
		return isExpireRenewals;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.isExpireRenewals
	 * @param isExpireRenewals  the value for t_mlb_record.isExpireRenewals
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setIsExpireRenewals(String isExpireRenewals) {
		this.isExpireRenewals = isExpireRenewals;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.MonthUsageData
	 * @return  the value of t_mlb_record.MonthUsageData
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getMonthUsageData() {
		return monthUsageData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.MonthUsageData
	 * @param monthUsageData  the value for t_mlb_record.MonthUsageData
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setMonthUsageData(String monthUsageData) {
		this.monthUsageData = monthUsageData;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_mlb_record.recordTime
	 * @return  the value of t_mlb_record.recordTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public String getRecordTime() {
		return recordTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_mlb_record.recordTime
	 * @param recordTime  the value for t_mlb_record.recordTime
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	public void setRecordTime(String recordTime) {
		this.recordTime = recordTime;
	}
}