package com.unicom.model;

import java.util.ArrayList;
import java.util.List;

public class TMlbTempExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public TMlbTempExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdIsNull() {
			addCriterion("wxOrderId is null");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdIsNotNull() {
			addCriterion("wxOrderId is not null");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdEqualTo(String value) {
			addCriterion("wxOrderId =", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdNotEqualTo(String value) {
			addCriterion("wxOrderId <>", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdGreaterThan(String value) {
			addCriterion("wxOrderId >", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdGreaterThanOrEqualTo(String value) {
			addCriterion("wxOrderId >=", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdLessThan(String value) {
			addCriterion("wxOrderId <", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdLessThanOrEqualTo(String value) {
			addCriterion("wxOrderId <=", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdLike(String value) {
			addCriterion("wxOrderId like", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdNotLike(String value) {
			addCriterion("wxOrderId not like", value, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdIn(List<String> values) {
			addCriterion("wxOrderId in", values, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdNotIn(List<String> values) {
			addCriterion("wxOrderId not in", values, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdBetween(String value1, String value2) {
			addCriterion("wxOrderId between", value1, value2, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andWxOrderIdNotBetween(String value1, String value2) {
			addCriterion("wxOrderId not between", value1, value2, "wxOrderId");
			return (Criteria) this;
		}

		public Criteria andOrderSignIsNull() {
			addCriterion("OrderSign is null");
			return (Criteria) this;
		}

		public Criteria andOrderSignIsNotNull() {
			addCriterion("OrderSign is not null");
			return (Criteria) this;
		}

		public Criteria andOrderSignEqualTo(String value) {
			addCriterion("OrderSign =", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignNotEqualTo(String value) {
			addCriterion("OrderSign <>", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignGreaterThan(String value) {
			addCriterion("OrderSign >", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignGreaterThanOrEqualTo(String value) {
			addCriterion("OrderSign >=", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignLessThan(String value) {
			addCriterion("OrderSign <", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignLessThanOrEqualTo(String value) {
			addCriterion("OrderSign <=", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignLike(String value) {
			addCriterion("OrderSign like", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignNotLike(String value) {
			addCriterion("OrderSign not like", value, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignIn(List<String> values) {
			addCriterion("OrderSign in", values, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignNotIn(List<String> values) {
			addCriterion("OrderSign not in", values, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignBetween(String value1, String value2) {
			addCriterion("OrderSign between", value1, value2, "orderSign");
			return (Criteria) this;
		}

		public Criteria andOrderSignNotBetween(String value1, String value2) {
			addCriterion("OrderSign not between", value1, value2, "orderSign");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoIsNull() {
			addCriterion("wxOrderNo is null");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoIsNotNull() {
			addCriterion("wxOrderNo is not null");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoEqualTo(String value) {
			addCriterion("wxOrderNo =", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoNotEqualTo(String value) {
			addCriterion("wxOrderNo <>", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoGreaterThan(String value) {
			addCriterion("wxOrderNo >", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoGreaterThanOrEqualTo(String value) {
			addCriterion("wxOrderNo >=", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoLessThan(String value) {
			addCriterion("wxOrderNo <", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoLessThanOrEqualTo(String value) {
			addCriterion("wxOrderNo <=", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoLike(String value) {
			addCriterion("wxOrderNo like", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoNotLike(String value) {
			addCriterion("wxOrderNo not like", value, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoIn(List<String> values) {
			addCriterion("wxOrderNo in", values, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoNotIn(List<String> values) {
			addCriterion("wxOrderNo not in", values, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoBetween(String value1, String value2) {
			addCriterion("wxOrderNo between", value1, value2, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andWxOrderNoNotBetween(String value1, String value2) {
			addCriterion("wxOrderNo not between", value1, value2, "wxOrderNo");
			return (Criteria) this;
		}

		public Criteria andAmountIsNull() {
			addCriterion("Amount is null");
			return (Criteria) this;
		}

		public Criteria andAmountIsNotNull() {
			addCriterion("Amount is not null");
			return (Criteria) this;
		}

		public Criteria andAmountEqualTo(Double value) {
			addCriterion("Amount =", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotEqualTo(Double value) {
			addCriterion("Amount <>", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThan(Double value) {
			addCriterion("Amount >", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountGreaterThanOrEqualTo(Double value) {
			addCriterion("Amount >=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThan(Double value) {
			addCriterion("Amount <", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountLessThanOrEqualTo(Double value) {
			addCriterion("Amount <=", value, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountIn(List<Double> values) {
			addCriterion("Amount in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotIn(List<Double> values) {
			addCriterion("Amount not in", values, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountBetween(Double value1, Double value2) {
			addCriterion("Amount between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andAmountNotBetween(Double value1, Double value2) {
			addCriterion("Amount not between", value1, value2, "amount");
			return (Criteria) this;
		}

		public Criteria andICCIDIsNull() {
			addCriterion("ICCID is null");
			return (Criteria) this;
		}

		public Criteria andICCIDIsNotNull() {
			addCriterion("ICCID is not null");
			return (Criteria) this;
		}

		public Criteria andICCIDEqualTo(String value) {
			addCriterion("ICCID =", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDNotEqualTo(String value) {
			addCriterion("ICCID <>", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDGreaterThan(String value) {
			addCriterion("ICCID >", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDGreaterThanOrEqualTo(String value) {
			addCriterion("ICCID >=", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDLessThan(String value) {
			addCriterion("ICCID <", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDLessThanOrEqualTo(String value) {
			addCriterion("ICCID <=", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDLike(String value) {
			addCriterion("ICCID like", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDNotLike(String value) {
			addCriterion("ICCID not like", value, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDIn(List<String> values) {
			addCriterion("ICCID in", values, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDNotIn(List<String> values) {
			addCriterion("ICCID not in", values, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDBetween(String value1, String value2) {
			addCriterion("ICCID between", value1, value2, "ICCID");
			return (Criteria) this;
		}

		public Criteria andICCIDNotBetween(String value1, String value2) {
			addCriterion("ICCID not between", value1, value2, "ICCID");
			return (Criteria) this;
		}

		public Criteria andSIMIsNull() {
			addCriterion("SIM is null");
			return (Criteria) this;
		}

		public Criteria andSIMIsNotNull() {
			addCriterion("SIM is not null");
			return (Criteria) this;
		}

		public Criteria andSIMEqualTo(String value) {
			addCriterion("SIM =", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMNotEqualTo(String value) {
			addCriterion("SIM <>", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMGreaterThan(String value) {
			addCriterion("SIM >", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMGreaterThanOrEqualTo(String value) {
			addCriterion("SIM >=", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMLessThan(String value) {
			addCriterion("SIM <", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMLessThanOrEqualTo(String value) {
			addCriterion("SIM <=", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMLike(String value) {
			addCriterion("SIM like", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMNotLike(String value) {
			addCriterion("SIM not like", value, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMIn(List<String> values) {
			addCriterion("SIM in", values, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMNotIn(List<String> values) {
			addCriterion("SIM not in", values, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMBetween(String value1, String value2) {
			addCriterion("SIM between", value1, value2, "SIM");
			return (Criteria) this;
		}

		public Criteria andSIMNotBetween(String value1, String value2) {
			addCriterion("SIM not between", value1, value2, "SIM");
			return (Criteria) this;
		}

		public Criteria andIMSIIsNull() {
			addCriterion("IMSI is null");
			return (Criteria) this;
		}

		public Criteria andIMSIIsNotNull() {
			addCriterion("IMSI is not null");
			return (Criteria) this;
		}

		public Criteria andIMSIEqualTo(String value) {
			addCriterion("IMSI =", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSINotEqualTo(String value) {
			addCriterion("IMSI <>", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSIGreaterThan(String value) {
			addCriterion("IMSI >", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSIGreaterThanOrEqualTo(String value) {
			addCriterion("IMSI >=", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSILessThan(String value) {
			addCriterion("IMSI <", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSILessThanOrEqualTo(String value) {
			addCriterion("IMSI <=", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSILike(String value) {
			addCriterion("IMSI like", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSINotLike(String value) {
			addCriterion("IMSI not like", value, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSIIn(List<String> values) {
			addCriterion("IMSI in", values, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSINotIn(List<String> values) {
			addCriterion("IMSI not in", values, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSIBetween(String value1, String value2) {
			addCriterion("IMSI between", value1, value2, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMSINotBetween(String value1, String value2) {
			addCriterion("IMSI not between", value1, value2, "IMSI");
			return (Criteria) this;
		}

		public Criteria andIMEIIsNull() {
			addCriterion("IMEI is null");
			return (Criteria) this;
		}

		public Criteria andIMEIIsNotNull() {
			addCriterion("IMEI is not null");
			return (Criteria) this;
		}

		public Criteria andIMEIEqualTo(String value) {
			addCriterion("IMEI =", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEINotEqualTo(String value) {
			addCriterion("IMEI <>", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEIGreaterThan(String value) {
			addCriterion("IMEI >", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEIGreaterThanOrEqualTo(String value) {
			addCriterion("IMEI >=", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEILessThan(String value) {
			addCriterion("IMEI <", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEILessThanOrEqualTo(String value) {
			addCriterion("IMEI <=", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEILike(String value) {
			addCriterion("IMEI like", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEINotLike(String value) {
			addCriterion("IMEI not like", value, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEIIn(List<String> values) {
			addCriterion("IMEI in", values, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEINotIn(List<String> values) {
			addCriterion("IMEI not in", values, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEIBetween(String value1, String value2) {
			addCriterion("IMEI between", value1, value2, "IMEI");
			return (Criteria) this;
		}

		public Criteria andIMEINotBetween(String value1, String value2) {
			addCriterion("IMEI not between", value1, value2, "IMEI");
			return (Criteria) this;
		}

		public Criteria andPackageNameIsNull() {
			addCriterion("PackageName is null");
			return (Criteria) this;
		}

		public Criteria andPackageNameIsNotNull() {
			addCriterion("PackageName is not null");
			return (Criteria) this;
		}

		public Criteria andPackageNameEqualTo(String value) {
			addCriterion("PackageName =", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotEqualTo(String value) {
			addCriterion("PackageName <>", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameGreaterThan(String value) {
			addCriterion("PackageName >", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameGreaterThanOrEqualTo(String value) {
			addCriterion("PackageName >=", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameLessThan(String value) {
			addCriterion("PackageName <", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameLessThanOrEqualTo(String value) {
			addCriterion("PackageName <=", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameLike(String value) {
			addCriterion("PackageName like", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotLike(String value) {
			addCriterion("PackageName not like", value, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameIn(List<String> values) {
			addCriterion("PackageName in", values, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotIn(List<String> values) {
			addCriterion("PackageName not in", values, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameBetween(String value1, String value2) {
			addCriterion("PackageName between", value1, value2, "packageName");
			return (Criteria) this;
		}

		public Criteria andPackageNameNotBetween(String value1, String value2) {
			addCriterion("PackageName not between", value1, value2, "packageName");
			return (Criteria) this;
		}

		public Criteria andPayStateIsNull() {
			addCriterion("PayState is null");
			return (Criteria) this;
		}

		public Criteria andPayStateIsNotNull() {
			addCriterion("PayState is not null");
			return (Criteria) this;
		}

		public Criteria andPayStateEqualTo(String value) {
			addCriterion("PayState =", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateNotEqualTo(String value) {
			addCriterion("PayState <>", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateGreaterThan(String value) {
			addCriterion("PayState >", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateGreaterThanOrEqualTo(String value) {
			addCriterion("PayState >=", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateLessThan(String value) {
			addCriterion("PayState <", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateLessThanOrEqualTo(String value) {
			addCriterion("PayState <=", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateLike(String value) {
			addCriterion("PayState like", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateNotLike(String value) {
			addCriterion("PayState not like", value, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateIn(List<String> values) {
			addCriterion("PayState in", values, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateNotIn(List<String> values) {
			addCriterion("PayState not in", values, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateBetween(String value1, String value2) {
			addCriterion("PayState between", value1, value2, "payState");
			return (Criteria) this;
		}

		public Criteria andPayStateNotBetween(String value1, String value2) {
			addCriterion("PayState not between", value1, value2, "payState");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("PayTime is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("PayTime is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(String value) {
			addCriterion("PayTime =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(String value) {
			addCriterion("PayTime <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(String value) {
			addCriterion("PayTime >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(String value) {
			addCriterion("PayTime >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(String value) {
			addCriterion("PayTime <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(String value) {
			addCriterion("PayTime <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLike(String value) {
			addCriterion("PayTime like", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotLike(String value) {
			addCriterion("PayTime not like", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<String> values) {
			addCriterion("PayTime in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<String> values) {
			addCriterion("PayTime not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(String value1, String value2) {
			addCriterion("PayTime between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(String value1, String value2) {
			addCriterion("PayTime not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CreateTime is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CreateTime is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(String value) {
			addCriterion("CreateTime =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(String value) {
			addCriterion("CreateTime <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(String value) {
			addCriterion("CreateTime >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("CreateTime >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(String value) {
			addCriterion("CreateTime <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(String value) {
			addCriterion("CreateTime <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLike(String value) {
			addCriterion("CreateTime like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotLike(String value) {
			addCriterion("CreateTime not like", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<String> values) {
			addCriterion("CreateTime in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<String> values) {
			addCriterion("CreateTime not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(String value1, String value2) {
			addCriterion("CreateTime between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(String value1, String value2) {
			addCriterion("CreateTime not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andPayMenterIsNull() {
			addCriterion("PayMenter is null");
			return (Criteria) this;
		}

		public Criteria andPayMenterIsNotNull() {
			addCriterion("PayMenter is not null");
			return (Criteria) this;
		}

		public Criteria andPayMenterEqualTo(String value) {
			addCriterion("PayMenter =", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterNotEqualTo(String value) {
			addCriterion("PayMenter <>", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterGreaterThan(String value) {
			addCriterion("PayMenter >", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterGreaterThanOrEqualTo(String value) {
			addCriterion("PayMenter >=", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterLessThan(String value) {
			addCriterion("PayMenter <", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterLessThanOrEqualTo(String value) {
			addCriterion("PayMenter <=", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterLike(String value) {
			addCriterion("PayMenter like", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterNotLike(String value) {
			addCriterion("PayMenter not like", value, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterIn(List<String> values) {
			addCriterion("PayMenter in", values, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterNotIn(List<String> values) {
			addCriterion("PayMenter not in", values, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterBetween(String value1, String value2) {
			addCriterion("PayMenter between", value1, value2, "payMenter");
			return (Criteria) this;
		}

		public Criteria andPayMenterNotBetween(String value1, String value2) {
			addCriterion("PayMenter not between", value1, value2, "payMenter");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderIsNull() {
			addCriterion("isToActiveOrder is null");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderIsNotNull() {
			addCriterion("isToActiveOrder is not null");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderEqualTo(String value) {
			addCriterion("isToActiveOrder =", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderNotEqualTo(String value) {
			addCriterion("isToActiveOrder <>", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderGreaterThan(String value) {
			addCriterion("isToActiveOrder >", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderGreaterThanOrEqualTo(String value) {
			addCriterion("isToActiveOrder >=", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderLessThan(String value) {
			addCriterion("isToActiveOrder <", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderLessThanOrEqualTo(String value) {
			addCriterion("isToActiveOrder <=", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderLike(String value) {
			addCriterion("isToActiveOrder like", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderNotLike(String value) {
			addCriterion("isToActiveOrder not like", value, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderIn(List<String> values) {
			addCriterion("isToActiveOrder in", values, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderNotIn(List<String> values) {
			addCriterion("isToActiveOrder not in", values, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderBetween(String value1, String value2) {
			addCriterion("isToActiveOrder between", value1, value2, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsToActiveOrderNotBetween(String value1, String value2) {
			addCriterion("isToActiveOrder not between", value1, value2, "isToActiveOrder");
			return (Criteria) this;
		}

		public Criteria andIsPushIsNull() {
			addCriterion("isPush is null");
			return (Criteria) this;
		}

		public Criteria andIsPushIsNotNull() {
			addCriterion("isPush is not null");
			return (Criteria) this;
		}

		public Criteria andIsPushEqualTo(String value) {
			addCriterion("isPush =", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushNotEqualTo(String value) {
			addCriterion("isPush <>", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushGreaterThan(String value) {
			addCriterion("isPush >", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushGreaterThanOrEqualTo(String value) {
			addCriterion("isPush >=", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushLessThan(String value) {
			addCriterion("isPush <", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushLessThanOrEqualTo(String value) {
			addCriterion("isPush <=", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushLike(String value) {
			addCriterion("isPush like", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushNotLike(String value) {
			addCriterion("isPush not like", value, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushIn(List<String> values) {
			addCriterion("isPush in", values, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushNotIn(List<String> values) {
			addCriterion("isPush not in", values, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushBetween(String value1, String value2) {
			addCriterion("isPush between", value1, value2, "isPush");
			return (Criteria) this;
		}

		public Criteria andIsPushNotBetween(String value1, String value2) {
			addCriterion("isPush not between", value1, value2, "isPush");
			return (Criteria) this;
		}

		public Criteria andHoldNameIsNull() {
			addCriterion("holdName is null");
			return (Criteria) this;
		}

		public Criteria andHoldNameIsNotNull() {
			addCriterion("holdName is not null");
			return (Criteria) this;
		}

		public Criteria andHoldNameEqualTo(String value) {
			addCriterion("holdName =", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameNotEqualTo(String value) {
			addCriterion("holdName <>", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameGreaterThan(String value) {
			addCriterion("holdName >", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameGreaterThanOrEqualTo(String value) {
			addCriterion("holdName >=", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameLessThan(String value) {
			addCriterion("holdName <", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameLessThanOrEqualTo(String value) {
			addCriterion("holdName <=", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameLike(String value) {
			addCriterion("holdName like", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameNotLike(String value) {
			addCriterion("holdName not like", value, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameIn(List<String> values) {
			addCriterion("holdName in", values, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameNotIn(List<String> values) {
			addCriterion("holdName not in", values, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameBetween(String value1, String value2) {
			addCriterion("holdName between", value1, value2, "holdName");
			return (Criteria) this;
		}

		public Criteria andHoldNameNotBetween(String value1, String value2) {
			addCriterion("holdName not between", value1, value2, "holdName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameIsNull() {
			addCriterion("oldPackageName is null");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameIsNotNull() {
			addCriterion("oldPackageName is not null");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameEqualTo(String value) {
			addCriterion("oldPackageName =", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameNotEqualTo(String value) {
			addCriterion("oldPackageName <>", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameGreaterThan(String value) {
			addCriterion("oldPackageName >", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameGreaterThanOrEqualTo(String value) {
			addCriterion("oldPackageName >=", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameLessThan(String value) {
			addCriterion("oldPackageName <", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameLessThanOrEqualTo(String value) {
			addCriterion("oldPackageName <=", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameLike(String value) {
			addCriterion("oldPackageName like", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameNotLike(String value) {
			addCriterion("oldPackageName not like", value, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameIn(List<String> values) {
			addCriterion("oldPackageName in", values, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameNotIn(List<String> values) {
			addCriterion("oldPackageName not in", values, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameBetween(String value1, String value2) {
			addCriterion("oldPackageName between", value1, value2, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andOldPackageNameNotBetween(String value1, String value2) {
			addCriterion("oldPackageName not between", value1, value2, "oldPackageName");
			return (Criteria) this;
		}

		public Criteria andIsFirstIsNull() {
			addCriterion("isFirst is null");
			return (Criteria) this;
		}

		public Criteria andIsFirstIsNotNull() {
			addCriterion("isFirst is not null");
			return (Criteria) this;
		}

		public Criteria andIsFirstEqualTo(String value) {
			addCriterion("isFirst =", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstNotEqualTo(String value) {
			addCriterion("isFirst <>", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstGreaterThan(String value) {
			addCriterion("isFirst >", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstGreaterThanOrEqualTo(String value) {
			addCriterion("isFirst >=", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstLessThan(String value) {
			addCriterion("isFirst <", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstLessThanOrEqualTo(String value) {
			addCriterion("isFirst <=", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstLike(String value) {
			addCriterion("isFirst like", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstNotLike(String value) {
			addCriterion("isFirst not like", value, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstIn(List<String> values) {
			addCriterion("isFirst in", values, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstNotIn(List<String> values) {
			addCriterion("isFirst not in", values, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstBetween(String value1, String value2) {
			addCriterion("isFirst between", value1, value2, "isFirst");
			return (Criteria) this;
		}

		public Criteria andIsFirstNotBetween(String value1, String value2) {
			addCriterion("isFirst not between", value1, value2, "isFirst");
			return (Criteria) this;
		}

		public Criteria andSimStateIsNull() {
			addCriterion("simState is null");
			return (Criteria) this;
		}

		public Criteria andSimStateIsNotNull() {
			addCriterion("simState is not null");
			return (Criteria) this;
		}

		public Criteria andSimStateEqualTo(String value) {
			addCriterion("simState =", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateNotEqualTo(String value) {
			addCriterion("simState <>", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateGreaterThan(String value) {
			addCriterion("simState >", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateGreaterThanOrEqualTo(String value) {
			addCriterion("simState >=", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateLessThan(String value) {
			addCriterion("simState <", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateLessThanOrEqualTo(String value) {
			addCriterion("simState <=", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateLike(String value) {
			addCriterion("simState like", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateNotLike(String value) {
			addCriterion("simState not like", value, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateIn(List<String> values) {
			addCriterion("simState in", values, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateNotIn(List<String> values) {
			addCriterion("simState not in", values, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateBetween(String value1, String value2) {
			addCriterion("simState between", value1, value2, "simState");
			return (Criteria) this;
		}

		public Criteria andSimStateNotBetween(String value1, String value2) {
			addCriterion("simState not between", value1, value2, "simState");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanIsNull() {
			addCriterion("activeTimespan is null");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanIsNotNull() {
			addCriterion("activeTimespan is not null");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanEqualTo(String value) {
			addCriterion("activeTimespan =", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanNotEqualTo(String value) {
			addCriterion("activeTimespan <>", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanGreaterThan(String value) {
			addCriterion("activeTimespan >", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanGreaterThanOrEqualTo(String value) {
			addCriterion("activeTimespan >=", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanLessThan(String value) {
			addCriterion("activeTimespan <", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanLessThanOrEqualTo(String value) {
			addCriterion("activeTimespan <=", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanLike(String value) {
			addCriterion("activeTimespan like", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanNotLike(String value) {
			addCriterion("activeTimespan not like", value, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanIn(List<String> values) {
			addCriterion("activeTimespan in", values, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanNotIn(List<String> values) {
			addCriterion("activeTimespan not in", values, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanBetween(String value1, String value2) {
			addCriterion("activeTimespan between", value1, value2, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andActiveTimespanNotBetween(String value1, String value2) {
			addCriterion("activeTimespan not between", value1, value2, "activeTimespan");
			return (Criteria) this;
		}

		public Criteria andPayEENameIsNull() {
			addCriterion("payEEName is null");
			return (Criteria) this;
		}

		public Criteria andPayEENameIsNotNull() {
			addCriterion("payEEName is not null");
			return (Criteria) this;
		}

		public Criteria andPayEENameEqualTo(String value) {
			addCriterion("payEEName =", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameNotEqualTo(String value) {
			addCriterion("payEEName <>", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameGreaterThan(String value) {
			addCriterion("payEEName >", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameGreaterThanOrEqualTo(String value) {
			addCriterion("payEEName >=", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameLessThan(String value) {
			addCriterion("payEEName <", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameLessThanOrEqualTo(String value) {
			addCriterion("payEEName <=", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameLike(String value) {
			addCriterion("payEEName like", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameNotLike(String value) {
			addCriterion("payEEName not like", value, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameIn(List<String> values) {
			addCriterion("payEEName in", values, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameNotIn(List<String> values) {
			addCriterion("payEEName not in", values, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameBetween(String value1, String value2) {
			addCriterion("payEEName between", value1, value2, "payEEName");
			return (Criteria) this;
		}

		public Criteria andPayEENameNotBetween(String value1, String value2) {
			addCriterion("payEEName not between", value1, value2, "payEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameIsNull() {
			addCriterion("accessEEName is null");
			return (Criteria) this;
		}

		public Criteria andAccessEENameIsNotNull() {
			addCriterion("accessEEName is not null");
			return (Criteria) this;
		}

		public Criteria andAccessEENameEqualTo(String value) {
			addCriterion("accessEEName =", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameNotEqualTo(String value) {
			addCriterion("accessEEName <>", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameGreaterThan(String value) {
			addCriterion("accessEEName >", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameGreaterThanOrEqualTo(String value) {
			addCriterion("accessEEName >=", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameLessThan(String value) {
			addCriterion("accessEEName <", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameLessThanOrEqualTo(String value) {
			addCriterion("accessEEName <=", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameLike(String value) {
			addCriterion("accessEEName like", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameNotLike(String value) {
			addCriterion("accessEEName not like", value, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameIn(List<String> values) {
			addCriterion("accessEEName in", values, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameNotIn(List<String> values) {
			addCriterion("accessEEName not in", values, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameBetween(String value1, String value2) {
			addCriterion("accessEEName between", value1, value2, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andAccessEENameNotBetween(String value1, String value2) {
			addCriterion("accessEEName not between", value1, value2, "accessEEName");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNull() {
			addCriterion("platformType is null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIsNotNull() {
			addCriterion("platformType is not null");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeEqualTo(String value) {
			addCriterion("platformType =", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotEqualTo(String value) {
			addCriterion("platformType <>", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThan(String value) {
			addCriterion("platformType >", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeGreaterThanOrEqualTo(String value) {
			addCriterion("platformType >=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThan(String value) {
			addCriterion("platformType <", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLessThanOrEqualTo(String value) {
			addCriterion("platformType <=", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeLike(String value) {
			addCriterion("platformType like", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotLike(String value) {
			addCriterion("platformType not like", value, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeIn(List<String> values) {
			addCriterion("platformType in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotIn(List<String> values) {
			addCriterion("platformType not in", values, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeBetween(String value1, String value2) {
			addCriterion("platformType between", value1, value2, "platformType");
			return (Criteria) this;
		}

		public Criteria andPlatformTypeNotBetween(String value1, String value2) {
			addCriterion("platformType not between", value1, value2, "platformType");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusIsNull() {
			addCriterion("RenewalsStatus is null");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusIsNotNull() {
			addCriterion("RenewalsStatus is not null");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusEqualTo(String value) {
			addCriterion("RenewalsStatus =", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusNotEqualTo(String value) {
			addCriterion("RenewalsStatus <>", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusGreaterThan(String value) {
			addCriterion("RenewalsStatus >", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusGreaterThanOrEqualTo(String value) {
			addCriterion("RenewalsStatus >=", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusLessThan(String value) {
			addCriterion("RenewalsStatus <", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusLessThanOrEqualTo(String value) {
			addCriterion("RenewalsStatus <=", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusLike(String value) {
			addCriterion("RenewalsStatus like", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusNotLike(String value) {
			addCriterion("RenewalsStatus not like", value, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusIn(List<String> values) {
			addCriterion("RenewalsStatus in", values, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusNotIn(List<String> values) {
			addCriterion("RenewalsStatus not in", values, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusBetween(String value1, String value2) {
			addCriterion("RenewalsStatus between", value1, value2, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusNotBetween(String value1, String value2) {
			addCriterion("RenewalsStatus not between", value1, value2, "renewalsStatus");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgIsNull() {
			addCriterion("RenewalsStatusMsg is null");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgIsNotNull() {
			addCriterion("RenewalsStatusMsg is not null");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgEqualTo(String value) {
			addCriterion("RenewalsStatusMsg =", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgNotEqualTo(String value) {
			addCriterion("RenewalsStatusMsg <>", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgGreaterThan(String value) {
			addCriterion("RenewalsStatusMsg >", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgGreaterThanOrEqualTo(String value) {
			addCriterion("RenewalsStatusMsg >=", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgLessThan(String value) {
			addCriterion("RenewalsStatusMsg <", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgLessThanOrEqualTo(String value) {
			addCriterion("RenewalsStatusMsg <=", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgLike(String value) {
			addCriterion("RenewalsStatusMsg like", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgNotLike(String value) {
			addCriterion("RenewalsStatusMsg not like", value, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgIn(List<String> values) {
			addCriterion("RenewalsStatusMsg in", values, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgNotIn(List<String> values) {
			addCriterion("RenewalsStatusMsg not in", values, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgBetween(String value1, String value2) {
			addCriterion("RenewalsStatusMsg between", value1, value2, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andRenewalsStatusMsgNotBetween(String value1, String value2) {
			addCriterion("RenewalsStatusMsg not between", value1, value2, "renewalsStatusMsg");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeIsNull() {
			addCriterion("SimFromType is null");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeIsNotNull() {
			addCriterion("SimFromType is not null");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeEqualTo(String value) {
			addCriterion("SimFromType =", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeNotEqualTo(String value) {
			addCriterion("SimFromType <>", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeGreaterThan(String value) {
			addCriterion("SimFromType >", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeGreaterThanOrEqualTo(String value) {
			addCriterion("SimFromType >=", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeLessThan(String value) {
			addCriterion("SimFromType <", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeLessThanOrEqualTo(String value) {
			addCriterion("SimFromType <=", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeLike(String value) {
			addCriterion("SimFromType like", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeNotLike(String value) {
			addCriterion("SimFromType not like", value, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeIn(List<String> values) {
			addCriterion("SimFromType in", values, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeNotIn(List<String> values) {
			addCriterion("SimFromType not in", values, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeBetween(String value1, String value2) {
			addCriterion("SimFromType between", value1, value2, "simFromType");
			return (Criteria) this;
		}

		public Criteria andSimFromTypeNotBetween(String value1, String value2) {
			addCriterion("SimFromType not between", value1, value2, "simFromType");
			return (Criteria) this;
		}

		public Criteria andTagIsNull() {
			addCriterion("Tag is null");
			return (Criteria) this;
		}

		public Criteria andTagIsNotNull() {
			addCriterion("Tag is not null");
			return (Criteria) this;
		}

		public Criteria andTagEqualTo(String value) {
			addCriterion("Tag =", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotEqualTo(String value) {
			addCriterion("Tag <>", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThan(String value) {
			addCriterion("Tag >", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThanOrEqualTo(String value) {
			addCriterion("Tag >=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThan(String value) {
			addCriterion("Tag <", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThanOrEqualTo(String value) {
			addCriterion("Tag <=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLike(String value) {
			addCriterion("Tag like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotLike(String value) {
			addCriterion("Tag not like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagIn(List<String> values) {
			addCriterion("Tag in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotIn(List<String> values) {
			addCriterion("Tag not in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagBetween(String value1, String value2) {
			addCriterion("Tag between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotBetween(String value1, String value2) {
			addCriterion("Tag not between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIsNull() {
			addCriterion("TradeType is null");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIsNotNull() {
			addCriterion("TradeType is not null");
			return (Criteria) this;
		}

		public Criteria andTradeTypeEqualTo(String value) {
			addCriterion("TradeType =", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotEqualTo(String value) {
			addCriterion("TradeType <>", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeGreaterThan(String value) {
			addCriterion("TradeType >", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeGreaterThanOrEqualTo(String value) {
			addCriterion("TradeType >=", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLessThan(String value) {
			addCriterion("TradeType <", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLessThanOrEqualTo(String value) {
			addCriterion("TradeType <=", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeLike(String value) {
			addCriterion("TradeType like", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotLike(String value) {
			addCriterion("TradeType not like", value, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeIn(List<String> values) {
			addCriterion("TradeType in", values, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotIn(List<String> values) {
			addCriterion("TradeType not in", values, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeBetween(String value1, String value2) {
			addCriterion("TradeType between", value1, value2, "tradeType");
			return (Criteria) this;
		}

		public Criteria andTradeTypeNotBetween(String value1, String value2) {
			addCriterion("TradeType not between", value1, value2, "tradeType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeIsNull() {
			addCriterion("SourceType is null");
			return (Criteria) this;
		}

		public Criteria andSourceTypeIsNotNull() {
			addCriterion("SourceType is not null");
			return (Criteria) this;
		}

		public Criteria andSourceTypeEqualTo(String value) {
			addCriterion("SourceType =", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeNotEqualTo(String value) {
			addCriterion("SourceType <>", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeGreaterThan(String value) {
			addCriterion("SourceType >", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeGreaterThanOrEqualTo(String value) {
			addCriterion("SourceType >=", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeLessThan(String value) {
			addCriterion("SourceType <", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeLessThanOrEqualTo(String value) {
			addCriterion("SourceType <=", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeLike(String value) {
			addCriterion("SourceType like", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeNotLike(String value) {
			addCriterion("SourceType not like", value, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeIn(List<String> values) {
			addCriterion("SourceType in", values, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeNotIn(List<String> values) {
			addCriterion("SourceType not in", values, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeBetween(String value1, String value2) {
			addCriterion("SourceType between", value1, value2, "sourceType");
			return (Criteria) this;
		}

		public Criteria andSourceTypeNotBetween(String value1, String value2) {
			addCriterion("SourceType not between", value1, value2, "sourceType");
			return (Criteria) this;
		}

		public Criteria andReceivablesIsNull() {
			addCriterion("Receivables is null");
			return (Criteria) this;
		}

		public Criteria andReceivablesIsNotNull() {
			addCriterion("Receivables is not null");
			return (Criteria) this;
		}

		public Criteria andReceivablesEqualTo(String value) {
			addCriterion("Receivables =", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesNotEqualTo(String value) {
			addCriterion("Receivables <>", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesGreaterThan(String value) {
			addCriterion("Receivables >", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesGreaterThanOrEqualTo(String value) {
			addCriterion("Receivables >=", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesLessThan(String value) {
			addCriterion("Receivables <", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesLessThanOrEqualTo(String value) {
			addCriterion("Receivables <=", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesLike(String value) {
			addCriterion("Receivables like", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesNotLike(String value) {
			addCriterion("Receivables not like", value, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesIn(List<String> values) {
			addCriterion("Receivables in", values, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesNotIn(List<String> values) {
			addCriterion("Receivables not in", values, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesBetween(String value1, String value2) {
			addCriterion("Receivables between", value1, value2, "receivables");
			return (Criteria) this;
		}

		public Criteria andReceivablesNotBetween(String value1, String value2) {
			addCriterion("Receivables not between", value1, value2, "receivables");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsIsNull() {
			addCriterion("isExpireRenewals is null");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsIsNotNull() {
			addCriterion("isExpireRenewals is not null");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsEqualTo(String value) {
			addCriterion("isExpireRenewals =", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsNotEqualTo(String value) {
			addCriterion("isExpireRenewals <>", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsGreaterThan(String value) {
			addCriterion("isExpireRenewals >", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsGreaterThanOrEqualTo(String value) {
			addCriterion("isExpireRenewals >=", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsLessThan(String value) {
			addCriterion("isExpireRenewals <", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsLessThanOrEqualTo(String value) {
			addCriterion("isExpireRenewals <=", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsLike(String value) {
			addCriterion("isExpireRenewals like", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsNotLike(String value) {
			addCriterion("isExpireRenewals not like", value, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsIn(List<String> values) {
			addCriterion("isExpireRenewals in", values, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsNotIn(List<String> values) {
			addCriterion("isExpireRenewals not in", values, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsBetween(String value1, String value2) {
			addCriterion("isExpireRenewals between", value1, value2, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andIsExpireRenewalsNotBetween(String value1, String value2) {
			addCriterion("isExpireRenewals not between", value1, value2, "isExpireRenewals");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataIsNull() {
			addCriterion("MonthUsageData is null");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataIsNotNull() {
			addCriterion("MonthUsageData is not null");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataEqualTo(String value) {
			addCriterion("MonthUsageData =", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataNotEqualTo(String value) {
			addCriterion("MonthUsageData <>", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataGreaterThan(String value) {
			addCriterion("MonthUsageData >", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataGreaterThanOrEqualTo(String value) {
			addCriterion("MonthUsageData >=", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataLessThan(String value) {
			addCriterion("MonthUsageData <", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataLessThanOrEqualTo(String value) {
			addCriterion("MonthUsageData <=", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataLike(String value) {
			addCriterion("MonthUsageData like", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataNotLike(String value) {
			addCriterion("MonthUsageData not like", value, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataIn(List<String> values) {
			addCriterion("MonthUsageData in", values, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataNotIn(List<String> values) {
			addCriterion("MonthUsageData not in", values, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataBetween(String value1, String value2) {
			addCriterion("MonthUsageData between", value1, value2, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andMonthUsageDataNotBetween(String value1, String value2) {
			addCriterion("MonthUsageData not between", value1, value2, "monthUsageData");
			return (Criteria) this;
		}

		public Criteria andRecordTimeIsNull() {
			addCriterion("recordTime is null");
			return (Criteria) this;
		}

		public Criteria andRecordTimeIsNotNull() {
			addCriterion("recordTime is not null");
			return (Criteria) this;
		}

		public Criteria andRecordTimeEqualTo(String value) {
			addCriterion("recordTime =", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeNotEqualTo(String value) {
			addCriterion("recordTime <>", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeGreaterThan(String value) {
			addCriterion("recordTime >", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeGreaterThanOrEqualTo(String value) {
			addCriterion("recordTime >=", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeLessThan(String value) {
			addCriterion("recordTime <", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeLessThanOrEqualTo(String value) {
			addCriterion("recordTime <=", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeLike(String value) {
			addCriterion("recordTime like", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeNotLike(String value) {
			addCriterion("recordTime not like", value, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeIn(List<String> values) {
			addCriterion("recordTime in", values, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeNotIn(List<String> values) {
			addCriterion("recordTime not in", values, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeBetween(String value1, String value2) {
			addCriterion("recordTime between", value1, value2, "recordTime");
			return (Criteria) this;
		}

		public Criteria andRecordTimeNotBetween(String value1, String value2) {
			addCriterion("recordTime not between", value1, value2, "recordTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_mlb_temp
	 * @mbg.generated  Sat May 12 18:10:29 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_mlb_temp
     *
     * @mbg.generated do_not_delete_during_merge Sat May 12 16:48:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}