package com.unicom.model;

public class TTaskPoint {

	
	public TTaskPoint() {
		super();
	}

	public TTaskPoint(String pointTime, String endTime, String reason, String error) {
		super();
		this.pointTime = pointTime;
		this.endTime = endTime;
		this.reason = reason;
		this.error = error;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task_point.id
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task_point.pointTime
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	private String pointTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task_point.endTime
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	private String endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task_point.reason
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	private String reason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_task_point.error
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	private String error;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task_point.id
	 * @return  the value of t_task_point.id
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task_point.id
	 * @param id  the value for t_task_point.id
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task_point.pointTime
	 * @return  the value of t_task_point.pointTime
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public String getPointTime() {
		return pointTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task_point.pointTime
	 * @param pointTime  the value for t_task_point.pointTime
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void setPointTime(String pointTime) {
		this.pointTime = pointTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task_point.endTime
	 * @return  the value of t_task_point.endTime
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public String getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task_point.endTime
	 * @param endTime  the value for t_task_point.endTime
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task_point.reason
	 * @return  the value of t_task_point.reason
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public String getReason() {
		return reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task_point.reason
	 * @param reason  the value for t_task_point.reason
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void setReason(String reason) {
		this.reason = reason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_task_point.error
	 * @return  the value of t_task_point.error
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public String getError() {
		return error;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_task_point.error
	 * @param error  the value for t_task_point.error
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void setError(String error) {
		this.error = error;
	}
}