package com.unicom.model;

import java.util.ArrayList;
import java.util.List;

public class TTaskPointExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public TTaskPointExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andPointTimeIsNull() {
			addCriterion("pointTime is null");
			return (Criteria) this;
		}

		public Criteria andPointTimeIsNotNull() {
			addCriterion("pointTime is not null");
			return (Criteria) this;
		}

		public Criteria andPointTimeEqualTo(String value) {
			addCriterion("pointTime =", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeNotEqualTo(String value) {
			addCriterion("pointTime <>", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeGreaterThan(String value) {
			addCriterion("pointTime >", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeGreaterThanOrEqualTo(String value) {
			addCriterion("pointTime >=", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeLessThan(String value) {
			addCriterion("pointTime <", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeLessThanOrEqualTo(String value) {
			addCriterion("pointTime <=", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeLike(String value) {
			addCriterion("pointTime like", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeNotLike(String value) {
			addCriterion("pointTime not like", value, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeIn(List<String> values) {
			addCriterion("pointTime in", values, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeNotIn(List<String> values) {
			addCriterion("pointTime not in", values, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeBetween(String value1, String value2) {
			addCriterion("pointTime between", value1, value2, "pointTime");
			return (Criteria) this;
		}

		public Criteria andPointTimeNotBetween(String value1, String value2) {
			addCriterion("pointTime not between", value1, value2, "pointTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("endTime is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("endTime is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(String value) {
			addCriterion("endTime =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(String value) {
			addCriterion("endTime <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(String value) {
			addCriterion("endTime >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(String value) {
			addCriterion("endTime >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(String value) {
			addCriterion("endTime <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(String value) {
			addCriterion("endTime <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLike(String value) {
			addCriterion("endTime like", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotLike(String value) {
			addCriterion("endTime not like", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<String> values) {
			addCriterion("endTime in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<String> values) {
			addCriterion("endTime not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(String value1, String value2) {
			addCriterion("endTime between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(String value1, String value2) {
			addCriterion("endTime not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andReasonIsNull() {
			addCriterion("reason is null");
			return (Criteria) this;
		}

		public Criteria andReasonIsNotNull() {
			addCriterion("reason is not null");
			return (Criteria) this;
		}

		public Criteria andReasonEqualTo(String value) {
			addCriterion("reason =", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotEqualTo(String value) {
			addCriterion("reason <>", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThan(String value) {
			addCriterion("reason >", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonGreaterThanOrEqualTo(String value) {
			addCriterion("reason >=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThan(String value) {
			addCriterion("reason <", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLessThanOrEqualTo(String value) {
			addCriterion("reason <=", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonLike(String value) {
			addCriterion("reason like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotLike(String value) {
			addCriterion("reason not like", value, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonIn(List<String> values) {
			addCriterion("reason in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotIn(List<String> values) {
			addCriterion("reason not in", values, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonBetween(String value1, String value2) {
			addCriterion("reason between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andReasonNotBetween(String value1, String value2) {
			addCriterion("reason not between", value1, value2, "reason");
			return (Criteria) this;
		}

		public Criteria andErrorIsNull() {
			addCriterion("error is null");
			return (Criteria) this;
		}

		public Criteria andErrorIsNotNull() {
			addCriterion("error is not null");
			return (Criteria) this;
		}

		public Criteria andErrorEqualTo(String value) {
			addCriterion("error =", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotEqualTo(String value) {
			addCriterion("error <>", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorGreaterThan(String value) {
			addCriterion("error >", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorGreaterThanOrEqualTo(String value) {
			addCriterion("error >=", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLessThan(String value) {
			addCriterion("error <", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLessThanOrEqualTo(String value) {
			addCriterion("error <=", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorLike(String value) {
			addCriterion("error like", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotLike(String value) {
			addCriterion("error not like", value, "error");
			return (Criteria) this;
		}

		public Criteria andErrorIn(List<String> values) {
			addCriterion("error in", values, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotIn(List<String> values) {
			addCriterion("error not in", values, "error");
			return (Criteria) this;
		}

		public Criteria andErrorBetween(String value1, String value2) {
			addCriterion("error between", value1, value2, "error");
			return (Criteria) this;
		}

		public Criteria andErrorNotBetween(String value1, String value2) {
			addCriterion("error not between", value1, value2, "error");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table t_task_point
	 * @mbg.generated  Sun May 13 12:26:08 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_task_point
     *
     * @mbg.generated do_not_delete_during_merge Sun May 13 09:56:08 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}