package com.unicom.mapping;

import com.unicom.model.TMlbRecord;
import com.unicom.model.TMlbRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TMlbRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	long countByExample(TMlbRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int deleteByExample(TMlbRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int insert(TMlbRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int insertSelective(TMlbRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	List<TMlbRecord> selectByExample(TMlbRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	TMlbRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int updateByExampleSelective(@Param("record") TMlbRecord record, @Param("example") TMlbRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int updateByExample(@Param("record") TMlbRecord record, @Param("example") TMlbRecordExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int updateByPrimaryKeySelective(TMlbRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_mlb_record
	 * @mbg.generated  Sat May 12 18:10:57 CST 2018
	 */
	int updateByPrimaryKey(TMlbRecord record);
}